version: '3.8'

services:
  frontend:
    build:
      context: ./nextjs_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./crewai_be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env  # 确保引用.env文件
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=crewai
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crewai
    ports:
      - "3307:3306"  # 修改为3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
